sudo: required
language: node_js
node_js:
  - 'node'
  - 8
services:
  - mongodb
  - elasticsearch
notifications:
  email: true
cache: yarn
before_install:
  - npm install -g yarn@1.10.1
  - lerna bootstrap
after_success: yarn coverage
