sudo: required
language: node_js
node_js:
  - 'node'
  - 8
services:
  - mongodb
  - elasticsearch
notifications:
  email: true
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success: lerna run coverage
